### PR TITLE
Remove suitesparse dependency

### LINKED ISSUE #74: SuiteSparse should not be a dependency
SuiteSparse should not be a dependency for python-igraph >= 0.10. Can you please remove it @vtraag ?

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #74

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Seeing this in a few linux tests:
```
======================================================================
ERROR: testAuthorityScore (tests.test_structural.CentralityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/python-igraph_1693597877983/test_tmp/tests/test_structural.py", line 438, in testAuthorityScore
    asc = g.authority_score()
igraph._igraph.InternalError: Error at src/linalg/arpack.c:1098: ARPACK error. -- No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV

======================================================================
FAIL: testHubScore (tests.test_atlas.GraphAtlasTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/python-igraph_1693597877983/test_tmp/tests/test_atlas.py", line 104, in testHubScore
    sc = g.hub_score()
igraph._igraph.InternalError: Error at src/linalg/arpack.c:1098: ARPACK error. -- No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/python-igraph_1693597877983/test_tmp/tests/test_atlas.py", line 106, in testHubScore
    self.assertTrue(
AssertionError: False is not true : Hub score calculation threw exception for graph #224: Error at src/linalg/arpack.c:1098: ARPACK error. -- No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV
```

@vtraag or @szhorvat, any clue what that might be cause by and why it only happens for some python versions and not others?

**Comment by xylar** [comment]
In the windows builds:
```
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:vendor\install\igraph\lib /LIBPATH:D:\bld\python-igraph_1693597949200\_h_env\libs /LIBPATH:D:\bld\python-igraph_1693597949200\_h_env /LIBPATH:D:\bld\python-igraph_1693597949200\_h_env\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" /LIBPATH:D:\bld\python-igraph_1693597949200\_h_env\Library\lib /LIBPATH:D:\bld\python-igraph_1693597949200\_h_env\Library\lib gmp.lib blas.lib cxsparse.lib glpk.lib lapack.lib libxml2.lib /EXPORT:PyInit__igraph build\temp.win-amd64-cpython-310\Release\src\_igraph\arpackobject.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\attributes.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\bfsiter.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\common.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\convert.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\dfsiter.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\edgeobject.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\edgeseqobject.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\error.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\filehandle.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\force_cpp_linker.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\graphobject.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\igraphmodule.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\indexing.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\operators.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\pyhelpers.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\random.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\vertexobject.obj build\temp.win-amd64-cpython-310\Release\src\_igraph\vertexseqobject.obj vendor\install\igraph\lib\igraph.lib /OUT:build\lib.win-amd64-cpython-310\igraph\_igraph.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\src\_igraph\_igraph.lib
  LINK : fatal error LNK1181: cannot open input file 'cxsparse.lib'
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe' failed with exit code 1181
  error: subprocess-exited-with-error
```

**Comment by szhorvat** [comment]
What version of ARPACK is it linking to now? I'm not familiar enough with conda to be able to figure this out.

**Comment by szhorvat** [comment]
If it's 3.9.0, can you check with 3.8.0 please? 3.9.0 is known to be buggy (fix is merged, waiting for 3.9.1). I'm not sure if what we see here is a symptom of this ARPACK-NG 3.9.0 bug, but if you link to that version, I strongly recommend using 3.8.0 instead.

**Comment by xylar** [comment]
@szhorvat, it's linking ot 3.7:
https://github.com/conda-forge/python-igraph-feedstock/blob/main/.ci_support/linux_64_python3.10.____cpython.yaml#L1-L2

**Comment by xylar** [comment]
the version of ARPACK is dictated by a conda-forge-wide pin that we presumably can't just modify here without breaking compatibility with other packages.

**Comment by xylar** [comment]
There seems to have been a PR to migrate to 3.8 about a year ago but no action has been taken:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3423

**Comment by szhorvat** [comment]
I'm not sure what's going on. The removal of SuiteSparse couldn't have caused this, since igraph simply doesn't use SuiteSparse anymore.  It's too late here for me to look into it now.

All I can say is that the test that is failing here is very extensive, and as a result a bit fragile. ARPACK won't always converge, and what happens may depend on the specific version of numerical libraries that are used (BLAC/LAPACK), the CPU architecture, and even compiler versions or optimization options. Thus reproing failures is difficult ... I've seen similar failures, but I thought that these were all resolved by now ... Either way, I would not consider _this specific_ failure to be serious, and it does not need to be a showstopper, if you're willing to go ahead.

**Comment by szhorvat** [comment]
For the Windows issue, remove `cxsparse` from here:

https://github.com/conda-forge/python-igraph-feedstock/blob/main/recipe/bld.bat#L21

**Comment by xylar** [comment]
Sounds good.  I can take care of those tomorrow.

Thanks @szhorvat!

**Comment by xylar** [comment]
@vtraag, are you okay with the 2 tests I disabled here?  If so, please merge at your convenience.

**Comment by szhorvat** [comment]
Before merging, it wouldn't be a bad idea to try to track down what exactly changed between this PR and the last successful one, #73.  Is it possible that the versions or builds of some dependencies changed?  Could the removal of SuiteSparse have indirectly changed which dependencies (or which versions of dependencies) are being used?  Can we confirm that re-adding SuiteSparse does not fix the issue in some mysterious way?

**Comment by xylar** [comment]
@szhorvat, I maintain a lot of packages (I think going on 400 at this point) so I don't really have time to investigate this one too deeply myself.  But I'm happy if @vtraag is interested in looking into it.

I believe we have seen intermittent failures like this for awhile now (but again it's hard for me to remember in detail if that was `python-igraph` or something else).  In the past, we have simply rerun the failing tests and they worked out after rerunning, but that isn't very convenient, particularly because the same process has to happen after a merge and we didn't always remember to do it.

I need this change to happen fairly urgently because the dependency via `suitesparse` on an older version of `metis` is blocking my work, so I would suggest we merge this first and investigate the issues after.  But I understand if that doesn't seem like a good approach to you all.

**Comment by szhorvat** [comment]
To be clear, I do consider this safe to merge.

In the longer term, it would be good to investigate it and re-enable the tests, but IMO this shouldn't block merging.

**Comment by vtraag** [comment]
Thanks for the PR @xylar!

Indeed, these test have failed for a (very) long time now. I did try to investigate them, I believe also with @ntamas, at some point. I don't remember the details, but I do know that we weren't able to resolve it. I'll open a separate issue for it, and track down what we've done before.

So, I'll go ahead and merge this now.

**Pull request merged**
