### PR TITLE
Added runtime dependency 'libiconv'.

### PR DESCRIPTION
**Pull request by ivirshup**
I've been having issues importing this library after installation on a couple centOS 6 servers. Based on [this stackoverflow](https://stackoverflow.com/questions/42222085/rpy2-doesnt-work-requires-libiconv-so-2) question, I saw adding `libiconv` manually fixed the issue. Based on that, it seems like `libiconv` is a runtime dependency (at least on some systems), so I thought I'd add it.

## Example failing build:

```sh
$ conda create -yn igraph_test python-igraph
```
<details>
<summary>Collapsed output</summary>
<pre>
Solving environment: done

\#\# Package Plan ##

  environment location: /scratch-new/isaacv/miniconda3/envs/igraph_test

  added / updated specs: 
    - python-igraph

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pycairo-1.15.4             |   py36h1b9232e_1          67 KB
    wheel-0.31.1               |           py36_0          62 KB
    ------------------------------------------------------------
                                           Total:         130 KB

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0                       
    cairo:           1.14.12-h7636065_2                 
    certifi:         2018.4.16-py36_0                   
    fontconfig:      2.12.6-h49f89f6_0                  
    freetype:        2.8-hab7d2ae_1                     
    glib:            2.56.1-h000015b_0                  
    gmp:             6.1.2-h6c8ec71_1                   
    icu:             58.2-h9c2bf20_1                    
    igraph:          0.7.1-4                 conda-forge
    libedit:         3.1.20170329-h6b74fdf_2            
    libffi:          3.2.1-hd88cf55_4                   
    libgcc-ng:       7.2.0-hdf63c60_3                   
    libpng:          1.6.34-hb9fc6fc_0                  
    libstdcxx-ng:    7.2.0-hdf63c60_3                   
    libxcb:          1.13-h1bed415_1                    
    libxml2:         2.9.8-hf84eae3_0                   
    ncurses:         6.1-hf484d3e_0                     
    openssl:         1.0.2o-h20670df_0                  
    pcre:            8.42-h439df22_0                    
    pip:             10.0.1-py36_0                      
    pixman:          0.34.0-hceecf20_3                  
    pycairo:         1.15.4-py36h1b9232e_1              
    python:          3.6.5-hc3d631a_2                   
    python-igraph:   0.7.1.post6-py36_4      conda-forge
    readline:        7.0-ha6073c6_4                     
    setuptools:      39.1.0-py36_0                      
    sqlite:          3.23.1-he433501_0                  
    tk:              8.6.7-hc745277_3                   
    wheel:           0.31.1-py36_0                      
    xz:              5.2.3-h5e939de_4                   
    zlib:            1.2.11-ha838bed_2      
...
</pre>
</details>

```
$ conda activate igraph_test
(igraph_test) $ python -c "import igraph"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch-new/isaacv/miniconda3/envs/igraph_test/lib/python3.6/site-packages/igraph/__init__.py", line 34, in <module>
    from igraph._igraph import *
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```

## Example passing build:

```sh
$ conda create -yn igraphlibiconv_test python-igraph libiconv
```
<details>
<summary>Collapsed output</summary>
<pre>
Solving environment: done

\#\# Package Plan ##

  environment location: /short/yf0/iv5408/miniconda3/envs/igraph_test

  added / updated specs: 
    - libiconv
    - python-igraph
    - python=3.6

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0                       
    cairo:           1.14.12-h7636065_2                 
    certifi:         2018.4.16-py36_0                   
    fontconfig:      2.12.6-h49f89f6_0                  
    freetype:        2.8-hab7d2ae_1                     
    glib:            2.56.1-h000015b_0                  
    gmp:             6.1.2-h6c8ec71_1                   
    icu:             58.2-h9c2bf20_1                    
    igraph:          0.7.1-4                 conda-forge
    libedit:         3.1.20170329-h6b74fdf_2            
    libffi:          3.2.1-hd88cf55_4                   
    libgcc-ng:       7.2.0-hdf63c60_3                   
    libiconv:        1.15-h63c8f33_5                    
    libpng:          1.6.34-hb9fc6fc_0                  
    libstdcxx-ng:    7.2.0-hdf63c60_3                   
    libxcb:          1.13-h1bed415_1                    
    libxml2:         2.9.8-hf84eae3_0                   
    ncurses:         6.1-hf484d3e_0                     
    openssl:         1.0.2o-h20670df_0                  
    pcre:            8.42-h439df22_0                    
    pip:             10.0.1-py36_0                      
    pixman:          0.34.0-hceecf20_3                  
    pycairo:         1.15.4-py36h1b9232e_1              
    python:          3.6.5-hc3d631a_2                   
    python-igraph:   0.7.1.post6-py36_4      conda-forge
    readline:        7.0-ha6073c6_4                     
    setuptools:      39.1.0-py36_0                      
    sqlite:          3.23.1-he433501_0                  
    tk:              8.6.7-hc745277_3                   
    wheel:           0.31.1-py36_0                      
    xz:              5.2.3-h5e939de_4                   
    zlib:            1.2.11-ha838bed_2     
...
</pre>
</details>

```
$ conda activate igraphlibiconv_test
(igraphlibiconv_test) $ python -c "import igraph" # Doesn't throw an error
```

### CODE REVIEW

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
sorry for the delay in getting this merged. I am trying to figure it out if this dependency belongs in libigraph instead, and why it did not get picked up during tests.

**Comment by ivirshup** [comment]
Are you able to reproduce the error?

The error seems system specific (installation works fine on my MacBook) so I'd imagine that's why the tests aren't picking it up.

**Comment by ivirshup** [comment]
Just checking in, any progress on that?

**Comment by sodre** [comment]
Fixing this issue on conda-forge/igraph-feedstock#8.

**Comment by ivirshup** [comment]
Cool, thanks for getting this fixed!

**Comment by sodre** [comment]
Please test on your side since I still have not been able to reproduce :)

**Comment by ivirshup** [comment]
Right! That part is important too.

Looks like it's working now!

**Pull request closed without merging**
